# Generated by Django 5.1.1 on 2024-10-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pace', '0002_profile_age_profile_education_level_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
    ]
